---

# https://wiki.archlinux.org/title/Internet_sharing#Enable_packet_forwarding
- name: Enable packet forwarding in sysctl.d
  ansible.builtin.copy:
    src: "{{ sysctld_file }}"
    dest: "/etc/sysctl.d/{{ sysctld_file }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Load sysctl.d config

- name: Netplan
  include_tasks: "netplan/main.yml"
